# Generated by Django 2.1.2 on 2018-10-22 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.IntegerField()),
                ('article_title', models.CharField(max_length=100)),
                ('article_content', models.CharField(max_length=2000)),
                ('article_author', models.CharField(max_length=50)),
                ('article_created', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
